# coding: utf-8

"""
    Strava API v3

    Strava API  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.summary_gear import SummaryGear  # noqa: F401,E501


class DetailedGear(SummaryGear):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'brand_name': 'str',
        'model_name': 'str',
        'frame_type': 'int',
        'description': 'str'
    }

    attribute_map = {
        'brand_name': 'brand_name',
        'model_name': 'model_name',
        'frame_type': 'frame_type',
        'description': 'description'
    }

    def __init__(self, brand_name=None, model_name=None, frame_type=None, description=None):  # noqa: E501
        """DetailedGear - a model defined in Swagger"""  # noqa: E501
        self._brand_name = None
        self._model_name = None
        self._frame_type = None
        self._description = None
        self.discriminator = None
        if brand_name is not None:
            self.brand_name = brand_name
        if model_name is not None:
            self.model_name = model_name
        if frame_type is not None:
            self.frame_type = frame_type
        if description is not None:
            self.description = description

    @property
    def brand_name(self):
        """Gets the brand_name of this DetailedGear.  # noqa: E501

        The gear's brand name.  # noqa: E501

        :return: The brand_name of this DetailedGear.  # noqa: E501
        :rtype: str
        """
        return self._brand_name

    @brand_name.setter
    def brand_name(self, brand_name):
        """Sets the brand_name of this DetailedGear.

        The gear's brand name.  # noqa: E501

        :param brand_name: The brand_name of this DetailedGear.  # noqa: E501
        :type: str
        """

        self._brand_name = brand_name

    @property
    def model_name(self):
        """Gets the model_name of this DetailedGear.  # noqa: E501

        The gear's model name.  # noqa: E501

        :return: The model_name of this DetailedGear.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this DetailedGear.

        The gear's model name.  # noqa: E501

        :param model_name: The model_name of this DetailedGear.  # noqa: E501
        :type: str
        """

        self._model_name = model_name

    @property
    def frame_type(self):
        """Gets the frame_type of this DetailedGear.  # noqa: E501

        The gear's frame type (bike only).  # noqa: E501

        :return: The frame_type of this DetailedGear.  # noqa: E501
        :rtype: int
        """
        return self._frame_type

    @frame_type.setter
    def frame_type(self, frame_type):
        """Sets the frame_type of this DetailedGear.

        The gear's frame type (bike only).  # noqa: E501

        :param frame_type: The frame_type of this DetailedGear.  # noqa: E501
        :type: int
        """

        self._frame_type = frame_type

    @property
    def description(self):
        """Gets the description of this DetailedGear.  # noqa: E501

        The gear's description.  # noqa: E501

        :return: The description of this DetailedGear.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this DetailedGear.

        The gear's description.  # noqa: E501

        :param description: The description of this DetailedGear.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetailedGear, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetailedGear):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
